version: '3.8'

services:
  db:
    image: pgvector/pgvector:postgres16
    container_name: learnix_db
    environment:
      POSTGRES_USER: learnix
      POSTGRES_PASSWORD: learnix_password
      POSTGRES_DB: learnix_db
    ports:
      - "5432:5432"
    volumes:
      - learnix_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  learnix_pgdata:
